#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: scripts/verify-live-activation-packet.sh [--require-live-ready] [--allow-provided-selftest] <live-activation-packet.json>

Verifies live activation packet integrity:
  - referenced proof artifacts exist
  - readiness bundle verifier passes
  - operator preflight verifier passes
  - selftest report is clean
  - packet pass summary matches referenced manifests
  - packet gate fields match referenced live-ready-gate report
  - final required commands use the guarded live launcher
  - embedded no-submit and protocol drift evidence is clean

Use --require-live-ready only when real operator live gates are expected to pass.
EOF
}

require_live_ready=0
allow_provided_selftest=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --require-live-ready)
      require_live_ready=1
      shift
      ;;
    --allow-provided-selftest)
      allow_provided_selftest=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    -*)
      echo "unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
    *)
      break
      ;;
  esac
done

packet="${1:-}"
if [[ -z "$packet" ]]; then
  usage >&2
  exit 2
fi
if [[ ! -f "$packet" ]]; then
  echo "missing activation packet: $packet" >&2
  exit 2
fi

need() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "missing required command: $1" >&2
    exit 2
  fi
}

need jq
need mktemp
need sed

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
work_root="$(mktemp -d "${TMPDIR:-/tmp}/polymarket-live-activation-verify.XXXXXX")"

cleanup() {
  rm -rf "$work_root"
}
trap cleanup EXIT

failures=0
fail() {
  echo "activation packet verification failed: $*" >&2
  failures=$((failures + 1))
}

abs_file() {
  local file="$1"
  (cd "$(dirname "$file")" && printf '%s/%s\n' "$(pwd -P)" "$(basename "$file")")
}

run_check() {
  local name="$1"
  shift
  local output="$work_root/${name//[^A-Za-z0-9_.-]/_}.out"
  set +e
  "$@" >"$output" 2>&1
  local rc=$?
  set -e
  if [[ "$rc" -ne 0 ]]; then
    fail "$name failed rc=$rc"
    sed 's/^/  /' "$output" >&2 || true
  fi
}

packet_abs="$(abs_file "$packet")"
packet_selftest_source="$(jq -r '.selftest.source // "unknown"' "$packet_abs")"
packet_json="$(jq -r '.artifacts.packet_json // empty' "$packet_abs")"
packet_markdown="$(jq -r '.artifacts.packet_markdown // empty' "$packet_abs")"
readiness_manifest="$(jq -r '.artifacts.readiness_manifest // empty' "$packet_abs")"
operator_manifest="$(jq -r '.artifacts.operator_preflight_manifest // empty' "$packet_abs")"
readiness_verification="$(jq -r '.artifacts.readiness_verification // empty' "$packet_abs")"
operator_verification="$(jq -r '.artifacts.operator_preflight_verification // empty' "$packet_abs")"
selftest_report="$(jq -r '.artifacts.verifier_selftest_report // empty' "$packet_abs")"
gate_report="$(jq -r '.artifacts.live_ready_gate_report // empty' "$packet_abs")"
live_env_template="$(jq -r '.artifacts.live_env_template // empty' "$packet_abs")"
launch_config_fingerprint="$(jq -r '.artifacts.launch_config_fingerprint // empty' "$packet_abs")"
release_binary="$(jq -r '.artifacts.release_binary // empty' "$packet_abs")"
build_provenance="$(jq -r '.artifacts.build_provenance // empty' "$packet_abs")"
activation_verification="$(jq -r '.artifacts.activation_packet_verification // empty' "$packet_abs")"

for item in \
  "packet_json:$packet_json" \
  "packet_markdown:$packet_markdown" \
  "readiness_manifest:$readiness_manifest" \
  "operator_preflight_manifest:$operator_manifest" \
  "readiness_verification:$readiness_verification" \
  "operator_preflight_verification:$operator_verification" \
  "verifier_selftest_report:$selftest_report" \
  "live_ready_gate_report:$gate_report" \
  "live_env_template:$live_env_template" \
  "launch_config_fingerprint:$launch_config_fingerprint" \
  "release_binary:$release_binary" \
  "build_provenance:$build_provenance"; do
  label="${item%%:*}"
  path="${item#*:}"
  if [[ -z "$path" ]]; then
    fail "missing artifact path: $label"
  elif [[ ! -f "$path" ]]; then
    fail "missing artifact file: $label path=$path"
  fi
done

if [[ -n "$activation_verification" && ! -f "$activation_verification" ]]; then
  fail "missing artifact file: activation_packet_verification path=$activation_verification"
fi

if [[ -n "$packet_json" && -f "$packet_json" && "$(abs_file "$packet_json")" != "$packet_abs" ]]; then
  fail "artifacts.packet_json does not point to verified packet"
fi

if [[ "$packet_selftest_source" != "generated" && "$allow_provided_selftest" -ne 1 ]]; then
  fail "selftest report was not generated by activation packet script: source=$packet_selftest_source"
fi

if [[ -f "$readiness_manifest" ]]; then
  if [[ "$require_live_ready" -eq 1 ]]; then
    run_check "readiness_bundle" \
      "$repo_root/scripts/verify-readiness-bundle.sh" --require-live-ready "$readiness_manifest"
  else
    run_check "readiness_bundle" \
      "$repo_root/scripts/verify-readiness-bundle.sh" "$readiness_manifest"
  fi
fi

if [[ -f "$operator_manifest" ]]; then
  if [[ "$require_live_ready" -eq 1 ]]; then
    run_check "operator_preflight" \
      "$repo_root/scripts/verify-live-operator-preflight.sh" --require-live-ready "$operator_manifest"
  else
    run_check "operator_preflight" \
      "$repo_root/scripts/verify-live-operator-preflight.sh" "$operator_manifest"
  fi
fi

if [[ -f "$selftest_report" ]]; then
  jq -e '
    .ok == true and
    (.checks | type == "array" and length >= 20) and
    all(.checks[]; .ok == true) and
    ([.checks[].name] | index("readiness_bundle_require_live_ready_matches_input") != null) and
    ([.checks[].name] | index("operator_preflight_require_live_ready_matches_input") != null) and
    ([.checks[].name] | index("live_ready_gate_matches_input") != null) and
    ([.checks[].name] | index("readiness_bundle_rejects_build_provenance_tamper") != null) and
    ([.checks[].name] | index("operator_preflight_rejects_runtime_panic_tamper") != null) and
    ([.checks[].name] | index("operator_preflight_rejects_launch_config_tamper") != null) and
    ([.checks[].name] | index("operator_preflight_rejects_template_shell_expansion") != null) and
    ([.checks[].name] | index("operator_preflight_rejects_underlying_live_state_tamper") != null) and
    ([.checks[].name] | index("operator_preflight_rejects_replay_calibration_tamper") != null) and
    ([.checks[].name] | index("activation_packet_baseline") != null) and
    ([.checks[].name] | index("activation_packet_rejects_provided_selftest_without_allow") != null) and
    ([.checks[].name] | index("activation_packet_require_live_ready_matches_input") != null) and
    ([.checks[].name] | index("activation_packet_rejects_gate_tamper") != null) and
    ([.checks[].name] | index("activation_packet_rejects_protocol_tamper") != null) and
    ([.checks[].name] | index("activation_packet_rejects_launch_config_tamper") != null) and
    ([.checks[].name] | index("activation_packet_rejects_no_submit_tamper") != null) and
    ([.checks[].name] | index("activation_packet_rejects_standard_no_submit_tamper") != null) and
    ([.checks[].name] | index("activation_packet_rejects_live_start_tamper") != null) and
    ([.checks[].name] | index("activation_packet_rejects_missing_no_paper") != null) and
    ([.checks[].name] | index("guarded_live_start_enforces_no_paper") != null) and
    ([.checks[].name] | index("guarded_live_start_rejects_paper_extra") != null) and
    ([.checks[].name] | index("guarded_live_start_rejects_unbound_extra") != null) and
    ([.checks[].name] | index("guarded_live_start_fixes_cwd_and_effective_env") != null) and
    ([.checks[].name] | index("guarded_live_start_rejects_tampered_packet") != null)
  ' "$selftest_report" >/dev/null || fail "selftest report is not clean"
fi

if [[ -f "$readiness_manifest" && -f "$operator_manifest" && -f "$gate_report" ]]; then
  jq -e \
    --arg packet_json "$packet_json" \
    --arg packet_markdown "$packet_markdown" \
    --arg readiness_manifest "$readiness_manifest" \
    --arg operator_manifest "$operator_manifest" \
    --arg readiness_verification "$readiness_verification" \
    --arg operator_verification "$operator_verification" \
    --arg selftest_report "$selftest_report" \
    --arg gate_report "$gate_report" \
    --arg live_env_template "$live_env_template" \
    --arg launch_config_fingerprint "$launch_config_fingerprint" \
    --arg release_binary "$release_binary" \
    --arg build_provenance "$build_provenance" \
    --slurpfile readiness "$readiness_manifest" \
    --slurpfile operator "$operator_manifest" \
    --slurpfile gate "$gate_report" \
    --slurpfile launch_config "$launch_config_fingerprint" \
    --slurpfile build "$build_provenance" \
    '
    .artifacts.packet_json == $packet_json and
    .artifacts.packet_markdown == $packet_markdown and
    .artifacts.readiness_manifest == $readiness_manifest and
    .artifacts.operator_preflight_manifest == $operator_manifest and
    .artifacts.readiness_verification == $readiness_verification and
    .artifacts.operator_preflight_verification == $operator_verification and
    .artifacts.verifier_selftest_report == $selftest_report and
    .artifacts.live_ready_gate_report == $gate_report and
    .artifacts.live_env_template == $live_env_template and
    .artifacts.launch_config_fingerprint == $launch_config_fingerprint and
    .artifacts.release_binary == $release_binary and
    .artifacts.build_provenance == $build_provenance and
    .launch_config == $launch_config[0] and
    .build == $build[0] and
    .paper_execution_binding == ($readiness[0].paper_execution_binding // {}) and
    .build.binary.path == $release_binary and
    .build.binary.sha256 == ($readiness[0].build.binary_sha256 // null) and
    .launch_config.combined_fingerprint == $operator[0].launch_config_fingerprint.combined_fingerprint and
    $operator[0].readiness_manifest == $readiness_manifest and
    $operator[0].release_build.binary_path == $release_binary and
    $operator[0].release_build.provenance_path == $build_provenance and
    $operator[0].release_build.binary_sha256 == .build.binary.sha256 and
    ((.can_enable_live != true) or (
      .paper_execution_binding.expected_producer_binary_sha256 == .build.binary.sha256 and
      .paper_execution_binding.producer_binary_sha256_values == [.build.binary.sha256] and
      .paper_execution_binding.paper_adapter.canonical_path == .paper_execution_binding.execution_profile.external_paper_executable_path and
      .paper_execution_binding.paper_adapter.executable_sha256 == .paper_execution_binding.execution_profile.external_paper_executable_sha256 and
      .paper_execution_binding.paper_live_profile_config == .launch_config.paper_live_profile_config and
      .paper_execution_binding.profit_compatibility_fingerprint_values == [.launch_config.profit_compatibility_fingerprint] and
      .paper_execution_binding.paper_evidence_eligible == true and
      .paper_execution_binding.live_route_compatible == false and
      .paper_execution_binding.activation_eligible_from_paper_alone == false
    )) and
    .no_live_trade_attempted == true and
    .pass_summary.readiness == ($readiness[0].pass_summary // {}) and
    .pass_summary.operator_preflight == ($operator[0].pass_summary // {}) and
    .pass_summary.selftest_ok == true and
    (.gate.rc | type == "number") and
    .gate.ok == (.can_enable_live // false) and
    .status == (if (.can_enable_live // false) then "live_ready" else "live_blocked" end) and
    ((.can_enable_live == true and .gate.rc == 0) or (.can_enable_live == false and .gate.rc != 0)) and
    .gate.ok == ($gate[0].ok // false) and
    .gate.readiness_state == ($gate[0].readiness.overall_state // "unknown") and
    .gate.readiness_blockers == ($gate[0].readiness.live_blocker_count // null) and
    .gate.operator_live_ready == ($gate[0].operator_preflight.live_ready // false) and
    .gate.operator_env_ready == ($gate[0].operator_preflight.env_summary.ready // false) and
    .gate.operator_env_blockers == ($gate[0].operator_preflight.env_summary.blocking_count // null) and
    .gate.live_trading_enabled == ($gate[0].final_live_env.live_trading_enabled // "false")
  ' "$packet_abs" >/dev/null || fail "packet summary or gate fields do not match referenced artifacts"

  jq -e '
    .launch_config.schema_version == 1 and
    .launch_config.algorithm == "keccak256-domain-separated-v1" and
    (.launch_config.config_fingerprint | type == "string" and test("^0x[0-9a-f]{64}$")) and
    (.launch_config.direct_live_identity_fingerprint | type == "string" and test("^0x[0-9a-f]{64}$")) and
    (.launch_config.combined_fingerprint | type == "string" and test("^0x[0-9a-f]{64}$")) and
    .launch_config.paper_live_profile_config.schema_version == 1 and
    .launch_config.paper_live_profile_config.execution_route == "legged_clob_paper" and
    (.launch_config.paper_live_profile_config.order_mode | type == "string") and
    (.launch_config.paper_live_profile_config.effective_order_type | type == "string") and
    (.launch_config.paper_live_profile_config.live_signature_type |
      type == "number" and . == floor and . >= 0 and . <= 3) and
    (.launch_config.paper_live_profile_config.full_clob_required | type == "boolean") and
    (.launch_config.paper_live_profile_config.match_live_position_size | type == "boolean")
  ' "$packet_abs" >/dev/null || fail "embedded launch config fingerprint is not clean"

  jq -e \
    --arg packet_json "$packet_json" \
    --arg readiness_manifest "$readiness_manifest" \
    --arg operator_manifest "$operator_manifest" \
    '
    .final_required_commands.verifier_selftest == (
      "scripts/readiness-verifier-selftest.sh --readiness-manifest " +
      $readiness_manifest +
      " --operator-preflight-manifest " +
      $operator_manifest
    ) and
    .final_required_commands.readiness_live_ready == (
      "scripts/verify-readiness-bundle.sh --require-live-ready " +
      $readiness_manifest
    ) and
    .final_required_commands.operator_live_ready == (
      "scripts/verify-live-operator-preflight.sh --require-live-ready " +
      $operator_manifest
    ) and
    .final_required_commands.live_ready_gate == (
      "scripts/live-ready-gate.sh --require-live-env-enabled --readiness-manifest " +
      $readiness_manifest +
      " --operator-preflight-manifest " +
      $operator_manifest
    ) and
    .final_required_commands.live_start == (
      "LIVE_TRADING_ENABLED=true scripts/guarded-live-start.sh --activation-packet " +
      $packet_json +
      " --confirm-live --no-paper"
    ) and
    ((.final_required_commands.live_start // "") | contains("cargo run -- --live") | not)
    and ((.final_required_commands.live_start // "") | endswith(" --no-paper"))
  ' "$packet_abs" >/dev/null || fail "final required commands are not clean"
fi

jq -e '
  .pass_summary.readiness.paper_ready == true and
  .pass_summary.readiness.paper_execution_canary_ok == true and
  .pass_summary.readiness.paper_scanner_trade_proof_ok == true and
  .pass_summary.readiness.paper_live_decision_path_parity_ok == true and
  (.pass_summary.readiness.paper_profitable_proven | type == "boolean") and
  (.pass_summary.readiness.hft_fastest_path_proven | type == "boolean") and
  .pass_summary.readiness.hft_ready == true and
  .pass_summary.readiness.ui_ready == true and
  .pass_summary.readiness.live_no_submission_ok == true and
  .pass_summary.readiness.global_no_live_scan_ok == true and
  .pass_summary.readiness.live_code_blocker_count == 0 and
  .pass_summary.readiness.source_static_blocker_count == 0 and
  .pass_summary.readiness.fail_closed_ok == true and
  .pass_summary.readiness.artifact_secret_scan_ok == true and
  .pass_summary.operator_preflight.cargo_status_ok == true and
  .pass_summary.operator_preflight.no_live_submission_ok == true and
  .pass_summary.operator_preflight.artifact_secret_value_scan_ok == true and
  .pass_summary.operator_preflight.live_trade_row_hits == 0 and
  .pass_summary.operator_preflight.combo_execution_journal_hits == 0 and
  .pass_summary.operator_preflight.standard_execution_journal_hits == 0 and
  .pass_summary.operator_preflight.submit_marker_hits == 0 and
  .pass_summary.operator_preflight.artifact_secret_value_hits == 0 and
  .no_submit.readiness_global_scan.ok == true and
  .no_submit.readiness_global_scan.live_trade_row_hits == 0 and
  .no_submit.readiness_global_scan.combo_execution_journal_hits == 0 and
  .no_submit.readiness_global_scan.standard_execution_journal_hits == 0 and
  .no_submit.readiness_global_scan.submit_marker_hits == 0 and
  .no_submit.operator_no_live_submission.ok == true and
  .no_submit.operator_no_live_submission.live_trade_row_hits == 0 and
  .no_submit.operator_no_live_submission.combo_execution_journal_hits == 0 and
  .no_submit.operator_no_live_submission.standard_execution_journal_hits == 0 and
  .no_submit.operator_no_live_submission.submit_marker_hits == 0 and
  .no_submit.artifact_secret_scan.readiness.ok == true and
  .no_submit.artifact_secret_scan.readiness.hit_count == 0 and
  .no_submit.artifact_secret_scan.operator.ok == true and
  .no_submit.artifact_secret_scan.operator.hit_count == 0
' "$packet_abs" >/dev/null || fail "embedded no-submit evidence is not clean"

jq -e '
  .protocol_drift.status == "ready" and
  (.protocol_drift.blockers | type == "array" and length == 0) and
  (.protocol_drift.source_urls | type == "array") and
  (.protocol_drift.source_urls | index("https://docs.polymarket.com/resources/contracts") != null) and
  (.protocol_drift.source_urls | index("https://docs.polymarket.com/developers/CLOB/introduction") != null) and
  (.protocol_drift.source_urls | index("https://docs.polymarket.com/market-makers/combos") != null) and
  ([
    .protocol_drift.checks[]?
    | select(
        .key == "combo_rfq_api_url" and
        .state == "ready" and
        .expected == "https://combos-rfq-api.polymarket.sh" and
        .observed == "https://combos-rfq-api.polymarket.sh" and
        .source_url == "https://docs.polymarket.com/market-makers/combos"
      )
  ] | length == 1) and
  ([
    .protocol_drift.checks[]?
    | select(
        .key == "combo_rfq_gateway_wss_url" and
        .state == "ready" and
        ((.expected // "") | split(",") | index("wss://combos-rfq-gateway-quoter.polymarket.sh/ws/rfq") != null) and
        .observed == "wss://combos-rfq-gateway-quoter.polymarket.sh/ws/rfq" and
        .source_url == "https://docs.polymarket.com/market-makers/combos"
      )
  ] | length == 1)
' "$packet_abs" >/dev/null || fail "embedded protocol drift evidence is not clean"

if [[ "$require_live_ready" -eq 1 ]]; then
  jq -e '
    .status == "live_ready" and
    .can_enable_live == true and
    .gate.ok == true and
    .gate.rc == 0 and
    (.gate.readiness_state == "ready" or .gate.readiness_state == "live_blocked") and
    .pass_summary.readiness.paper_profitable_proven == true and
    .pass_summary.readiness.hft_fastest_path_proven == true and
    .gate.operator_live_ready == true and
    .gate.operator_env_ready == true and
    .gate.operator_env_blockers == 0 and
    .pass_summary.operator_preflight.live_ready == true and
    .pass_summary.operator_preflight.env_audit_ready == true and
    .pass_summary.operator_preflight.env_audit_blocking_count == 0
  ' "$packet_abs" >/dev/null || fail "packet live-ready fields are not true"
fi

if [[ "$failures" -ne 0 ]]; then
  exit 1
fi

printf 'live_activation_packet_ok=1 packet=%s status=%s can_enable_live=%s\n' \
  "$packet_abs" \
  "$(jq -r '.status // "unknown"' "$packet_abs")" \
  "$(jq -r '.can_enable_live // false' "$packet_abs")"
